# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYeLoyFCXEzfvJNydmeCeOf66P3dESxK
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

row = df["Row ID"].to_numpy()
print(row)

date = df["Order Date"].to_numpy()
print(date)

ship = df["Ship Date"].to_numpy()
print(ship)

mode = df["Ship Mode"].to_numpy()
print(mode)

Customer = df["Customer ID"].to_numpy()
print(Customer)

name = df["Customer Name"].to_numpy()
print(name)

segment = df["Segment"].to_numpy()
print(segment)

country = df["Country"].to_numpy()
print(country)

state = df["State"].to_numpy()
print(state)

region = df["Region"].to_numpy()
print(region)

id = df["Product ID"].to_numpy()
print(id)

category = df["Category"].to_numpy()
print(category)

Sub_category = df["Sub-Category"].to_numpy()
print(Sub_category)

product = df["Product Name"].to_numpy()
print(product)

sale = df["Sales"].to_numpy()
print(sale)

print('Checking for missing values:')
display(df.isnull().sum())

# Convert 'Order Date' and 'Ship Date' to datetime objects
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

print('\nData types after conversion:')
display(df[['Order Date', 'Ship Date']].dtypes)

print('\nChecking for duplicate rows:')
duplicate_rows = df.duplicated().sum()
if duplicate_rows > 0:
    print(f'Found {duplicate_rows} duplicate rows. Removing duplicates...')
    df.drop_duplicates(inplace=True)
    print('Duplicates removed.')
else:
    print('No duplicate rows found.')

total_sales = df['Sales'].sum()
average_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()

print(f"Total Sales: {total_sales:,.2f}")
print(f"Average Sales: {average_sales:,.2f}")
print(f"Maximum Sales: {max_sales:,.2f}")
print(f"Minimum Sales: {min_sales:,.2f}")

print('\nDescriptive statistics for Sales:')
display(df['Sales'].describe())

"""## 4. Sales Trend Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

# Aggregate sales by Order Date to analyze trends over time
daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()

plt.figure(figsize=(15, 7))
sns.lineplot(x='Order Date', y='Sales', data=daily_sales)
plt.title('Sales Trend Over Time')
plt.xlabel('Order Date')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

"""## 5. Store/Product Analysis"""

# Sales by Region
sales_by_region = df.groupby('Region')['Sales'].sum().sort_values(ascending=False).reset_index()
print('\nSales by Region:')
display(sales_by_region)

plt.figure(figsize=(10, 6))
sns.barplot(x='Region', y='Sales', data=sales_by_region, palette='viridis')
plt.title('Total Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.show()

# Top 10 Best-Selling Products
products_sales = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10).reset_index()
print('\nTop 10 Best-Selling Products:')
display(products_sales)

plt.figure(figsize=(12, 7))
sns.barplot(x='Sales', y='Product Name', data=products_sales, palette='magma')
plt.title('Top 10 Best-Selling Products')
plt.xlabel('Total Sales')
plt.ylabel('Product Name')
plt.show()

# Top 10 Worst-Selling Products
products_sales_worst = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=True).head(10).reset_index()
print('\nTop 10 Worst-Selling Products:')
display(products_sales_worst)

plt.figure(figsize=(12, 7))
sns.barplot(x='Sales', y='Product Name', data=products_sales_worst, palette='cividis')
plt.title('Top 10 Worst-Selling Products')
plt.xlabel('Total Sales')
plt.ylabel('Product Name')
plt.show()

# Extract year, month, and day of week from Order Date
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month_name()
df['Order DayOfWeek'] = df['Order Date'].dt.day_name()

print('Extracted time components:')
display(df[['Order Date', 'Order Year', 'Order Month', 'Order DayOfWeek']].head())

"""## 8. Data Visualization"""

# Sales Distribution (Histogram)
plt.figure(figsize=(10, 6))
sns.histplot(df['Sales'], bins=50, kde=True)
plt.title('Distribution of Sales')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.show()

# Monthly Sales Trend
monthly_sales = df.groupby('Order Month')['Sales'].sum().reindex([    'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']).reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(x='Order Month', y='Sales', data=monthly_sales, palette='cubehelix')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# Yearly Sales Trend
yearly_sales = df.groupby('Order Year')['Sales'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Order Year', y='Sales', data=yearly_sales, palette='rocket')
plt.title('Yearly Sales Trend')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.show()